### PR TITLE
Update to qt5

### PR DESCRIPTION
**Pull request by haider8645**
Hello,

updated this tutorial for qt5.

Best.
Haider

### CODE REVIEW

**Comment by planthaber** [comment]
This request should go to a feature/qt5 branch, but I don't have the rights on the organization (@doudou can you promote me?).

**Comment by doudou** [comment]
Done

**Comment by planthaber** [comment]
Please change the PR to have the the feature/qt5 branch as target

**Comment by haider8645** [comment]
@planthaber  Could you please merge this in the feature/qt5 branch

**Comment by annaborn** [comment]
@planthaber Steffen, can you please take a look and merge it? the branch is changed

**Pull request merged**
